version: '3.8'

services:
  talentgate-web-traefik:
    container_name: talentgate-web-traefik
    image: traefik:latest
    restart: always
    command:
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--providers.docker.exposedbydefault=false'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - talentgate-web-net
    profiles:
      - prod

  talentgate-web:
    build: .
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=PathPrefix(`/`)'
      - 'traefik.http.routers.talentgate-api.entrypoints=web'
      - 'traefik.http.services.talentgate-api.loadbalancer.server.port=80'
    networks:
      - talentgate-web-net
    profiles:
      - prod

networks:
  talentgate-web-net:
    driver: bridge
